version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
        - 5000:443 

  SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrong_Password123#